// * [GoogleChromeLabs/input-knob](https://github.com/GoogleChromeLabs/input-knob)
{"32" : { "name" : "Bank Select LSB", CC : 32}, 
  "0" : { "name" : "Bank Select MSB", CC : 0}, 
  "7" : { "name" : "Level", CC : 7}, 
  "10" : { "name" : "Pan", CC : 10}, 
  "14" : { "name" : "Noise Filter Frequency", CC : 14}, 
  "15" : { "name" : "Noise Filter Type", CC : 15}, 
  "16" : { "name" : "Noise Filter Envelope", CC : 16}, 
  "17" : { "name" : "Noise Filter Resonance", CC : 17}, 
  "18" : { "name" : "Noise Attack/Rate", CC : 18}, 
  "19" : { "name" : "Noise Atk Mode", CC : 19}, 
  "20" : { "name" : "Noise Decay Type (E, L, G)", CC : 20}, 
  "21" : { "name" : "Noise Decay", CC : 21},
  "22" : { "name" : "Noise Decay Lo", CC : 22}, 
  "23" : { "name" : "Dist Amount", CC : 23}, 
  "24" : { "name" : "Dist Type", CC : 24}, 
  "25" : { "name" : "EQ Frequency", CC : 25}, 
  "26" : { "name" : "EQ Gain", CC : 26}, 
  "27" : { "name" : "Echo Feedback", CC : 27}, 
  "28" : { "name" : "Echo Amount", CC : 28}, 
  "61" : { "name" : "Echo BPM LSB", CC : 61}, 
  "29" : { "name" : "Echo BPM MSB", CC : 29}, 
  "30" : { "name" : "Tone Spectra", CC : 30}, 
  "46" : { "name" : "Tone Wave", CC : 46}, 
  "47" : { "name" : "Tone Timbre Decay", CC : 47}, 
  "48" : { "name" : "Tone Punch", CC : 48}, 
  "49" : { "name" : "Tone Decay Type (L, E)", CC : 49}, 
  "50" : { "name" : "Tone Decay", CC : 50}, 
  "51" : { "name" : "Tone Dec Lo", CC : 51}, 
  "52" : { "name" : "Tone Timbre", CC : 52}, 
  "53" : { "name" : "Tone Timb Envelope", CC : 53}, 
  "54" : { "name" : "Tone Bend Amount", CC : 54}, 
  "55" : { "name" : "Tone Bend Time", CC : 55}, 
  "56" : { "name" : "Click Level", CC : 56}, 
  "57" : { "name" : "Click Type", CC : 57}, 
  "58" : { "name" : "Mix Balance", CC : 58}, 
  "59" : { "name" : "Mute Group", CC : 59}, 
  "63" : { "name" : "Tone Pitch LSB", CC : 63}, 
  "31" : { "name" : "Tone Pitch MSB", CC : 31}, 
  "70" : { "name" : "Channel Focus", CC : 70}}
